name: intellihome_application
description: "IntelliHome IoT Smart Home Control Application"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.0
  flutter_lints: ^5.0.0
  home_widget: ^0.3.0
  geolocator: ^10.1.0
  http: ^1.1.0
  fl_chart: ^0.66.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  mailer: ^6.0.0

flutter:
  uses-material-design: true
